GET http://localhost:3000/api/product
Authorization: Bearer secret,
Content-Type: application/json

###
GET http://localhost:3000/api/product/cmfavzmea0002l69kwbx7c291
Content-Type: application/json

### 
PATCH http://localhost:3000/api/product/cmfavzmea0002l69kwbx7c291
Authorization: Bearer secret,
Content-Type: multipart/form-data

{
    "name":"",
    "price":0,
    "img":"",
    "desc":"",
    "removeImg":false
}

###
DELETE http://localhost:3000/api/product/cmfavzmea0002l69kwbx7c291
Authorization: Bearer secret,
Content-Type: application/json
